In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
%matplotlib inline

In [2]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:pgadmin1325@localhost:5432/edificiomiraflores_bd")

print(engine)

Engine(postgresql://postgres:***@localhost:5432/edificiomiraflores_bd)

In [3]:
df = pd.read_csv(
    "../data/recibosjulagosep.csv",
    sep=";",
    decimal=",",
    encoding="latin-1"
)

In [4]:
df['jul-26'] = df['jul-26'].fillna('')
df['ago-26'] = df['ago-26'].fillna('')
df['sep-26'] = df['sep-26'].fillna('')
df['oct-26'] = df['oct-26'].fillna('')
df['nov-26'] = df['nov-26'].fillna('')
df['dic-26'] = df['dic-26'].fillna('')
df['ene-27'] = df['ene-27'].fillna('')
df['feb-27'] = df['feb-27'].fillna('')
df['mar-27'] = df['mar-27'].fillna('')
df['abr-27'] = df['abr-27'].fillna('')
df['may-27'] = df['may-27'].fillna('')
df['jun-27'] = df['jun-27'].fillna('')
df['PISO'] = df['PISO'].astype('Int64')
df['3y4 dormi'] = df['3y4 dormi'].fillna('')
df['Morosos'] = df['Morosos'].fillna('')
df

,LETRA,PISO,NOMBRE Y APELLIDO,jul-26,ago-26,sep-26,oct-26,nov-26,dic-26,ene-27,feb-27,mar-27,abr-27,may-27,jun-27,3y4 dormi,Morosos,escidal
0,A,3,JESMY AMANDA PALENQUE,154.05,154.03,154.1,,,,,,,,,,,,NaN
1,B,3,NATHALIE CASTRO INOFUENTE,193.29,191.44,,,,,,,,,,,,,NaN
2,C,3,JOSE MANUEL BUSTILLOS,,,,,,,,,,,,,,,NaN
3,D,3,ABDON FELIPE SERNA OLAÑETA,92.91,,93.86,,,,,,,,,,,,NaN
4,E,3,JULIETA MAMANI DE NINA,,,,,,,,,,,,,x,x,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,C,21,"CIDAL LTDA,",,,,,,,,,,,,,,,x
104,B,22,FABIOLA LAURA VARGAS,,,,,,,,,,,,,,x,NaN
105,C,22,"CIDAL LTDA,",,,,,,,,,,,,,,,x
106,AC,<NA>,LAVANDERIA,,,,,,,,,,,,,,,NaN
107,NaN,<NA>,GIMNASIO,,,,,,,,,,,,,,,NaN

In [5]:
df_departamentos = pd.read_sql("SELECT * FROM departamentos;", engine)
df_departamentos.head()

,id_departamento,piso,numero,id_copropietario,nro_cuartos,superficie,tipo,id_edificio
0,1,3,A,None,None,None,None,1
1,2,3,B,None,None,None,None,1
2,3,3,C,None,None,None,None,1
3,4,3,D,None,None,None,None,1
4,5,3,E,None,None,None,None,1

In [ ]:
# Datos de entrada
current_date = "28/08/2026"
nro_recibo = 578

In [9]:
def generar_recibo_multiconcepto(filename="recibo_multiconcepto.pdf"):

    # Tamaño Media Hoja Carta (8.5 x 5.5 pulgadas)
    doc = SimpleDocTemplate(
        filename,
        pagesize=(8.5 * inch, 5.5 * inch),
        rightMargin=25,
        leftMargin=25,
        topMargin=18,
        bottomMargin=18
    )

    story = []
    styles = getSampleStyleSheet()

    # ---------------------------------------------------------
    # ESTILOS
    # ---------------------------------------------------------

    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=12,
        leading=14,
        textColor=colors.HexColor('#1B365D')
    )

    right_text = ParagraphStyle(
        'RightText',
        parent=styles['Normal'],
        fontSize=8,
        leading=10,
        alignment=2
    )

    bold_style = ParagraphStyle(
        'BoldStyle',
        parent=styles['Normal'],
        fontSize=8,
        leading=10,
        fontName='Helvetica-Bold',
        textColor=colors.white
    )

    bold_style_black = ParagraphStyle(
        'BoldStyleBlack',
        parent=styles['Normal'],
        fontSize=8,
        leading=10,
        fontName='Helvetica-Bold',
        textColor=colors.black
    )

    cell_style = ParagraphStyle(
        'CellStyle',
        parent=styles['Normal'],
        fontSize=8,
        leading=10,
        textColor=colors.black
    )

    ANCHO_UTIL = 7.8 * inch

    # ---------------------------------------------------------
    # 1. ENCABEZADO
    # ---------------------------------------------------------

    header_data = [
        [
            Paragraph(
                "<b>EDIFICIO MIRAFLORES NORTE</b>"
                "<br/>"
                "<font size=7 color='#555555'>Administración de Expensas</font>",
                title_style
            ),

            Paragraph(
                "<b>RECIBO DE EXPENSAS</b>"
                "<br/>"
                f"N°: {nro_recibo}-2026 | Fecha: {current_date}",
                right_text
            )
        ]
    ]

    header_table = Table(
        header_data,
        colWidths=[
            ANCHO_UTIL * 0.55,
            ANCHO_UTIL * 0.45
        ]
    )

    header_table.setStyle(
        TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP')
        ])
    )

    story.append(header_table)
    story.append(Spacer(1, 4))

    # ---------------------------------------------------------
    # 2. DATOS GENERALES
    # ---------------------------------------------------------

    info_data = [
        [
            Paragraph("<b>Dpto:</b> 4B", cell_style),
            Paragraph("<b>Propietario:</b> Juan Pérez", cell_style),
            Paragraph("<b>Estado:</b> Cancelado", cell_style)
        ]
    ]

    info_table = Table(
        info_data,
        colWidths=[
            ANCHO_UTIL * 0.25,
            ANCHO_UTIL * 0.50,
            ANCHO_UTIL * 0.25
        ]
    )

    info_table.setStyle(
        TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F4F6F8')),
            ('PADDING', (0, 0), (-1, -1), 4),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LINEBELOW', (0, -1), (-1, -1), 1, colors.HexColor('#D0D7DE')),
        ])
    )

    story.append(info_table)
    story.append(Spacer(1, 6))

    # ---------------------------------------------------------
    # 3. TABLA DE CONCEPTOS
    # ---------------------------------------------------------

    items_data = [
        [
            Paragraph("<b>Periodo/Cant.</b>", bold_style),
            Paragraph("<b>Concepto</b>", bold_style),
            Paragraph(
                "<b>Monto ($)</b>",
                ParagraphStyle(
                    'MontoHeader',
                    parent=bold_style,
                    alignment=2
                )
            )
        ],

        [
            Paragraph("Julio 2026", cell_style),
            Paragraph("Expensas Ordinarias", cell_style),
            Paragraph("120.00", right_text)
        ],

        [
            Paragraph("Agosto 2026", cell_style),
            Paragraph("Expensas Ordinarias", cell_style),
            Paragraph("120.00", right_text)
        ],

        [
            Paragraph("05/09/2026", cell_style),
            Paragraph("Alquiler Parrillero (Evento)", cell_style),
            Paragraph("35.00", right_text)
        ],

        [
            Paragraph("Jul - Ago", cell_style),
            Paragraph("Fondo de Reserva (2 meses)", cell_style),
            Paragraph("20.00", right_text)
        ],

        [
            Paragraph("<b>TOTAL A PAGAR</b>", bold_style_black),
            Paragraph("", cell_style),
            Paragraph(
                "<b>$295.00</b>",
                ParagraphStyle(
                    'MontoTotal',
                    parent=bold_style_black,
                    alignment=2
                )
            )
        ]
    ]

    items_table = Table(
        items_data,
        colWidths=[
            ANCHO_UTIL * 0.25,
            ANCHO_UTIL * 0.55,
            ANCHO_UTIL * 0.20
        ]
    )

    items_table.setStyle(
        TableStyle([
            # Encabezado
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1B365D')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),

            # Espaciado
            ('PADDING', (0, 0), (-1, -1), 3),

            # Líneas
            ('GRID', (0, 0), (-1, -2), 0.5, colors.HexColor('#E1E4E8')),

            # Total
            ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#EAECEE')),
            ('SPAN', (0, -1), (1, -1)),
            ('LINEABOVE', (0, -1), (-1, -1), 1, colors.HexColor('#1B365D')),
        ])
    )

    story.append(items_table)

    # Espacio final
    story.append(Spacer(1, 8))

    # ---------------------------------------------------------
    # 4. PIE DEL RECIBO
    # ---------------------------------------------------------

    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=7,
        leading=9,
        alignment=1,
        textColor=colors.HexColor('#666666')
    )

    story.append(
        Paragraph(
            "Documento generado por la Administración del Edificio Miraflores Norte",
            footer_style
        )
    )

    # ---------------------------------------------------------
    # GENERAR PDF
    # ---------------------------------------------------------

    doc.build(story)

In [14]:
for indice, fila in df.iterrows():
    print(fila)
    #Buscar en recibos desde Julio 26, hasta a Junio 27
    for nombre_mes, monto in fila.iloc[3:14].items():
        expensas_despues_julio = []
        # Verifica si el mes de la expensa esta asignado a algun recibo
        #print(f"{nombre_mes}, {monto}")
        """
        if str(monto).strip() != "":
            numero_meses_adeudados = numero_meses_adeudados + 1
            monto_adeudado = monto_adeudado + monto
            nro_columnas = nro_columnas + 1
            if nro_columnas < 11:
                montos_x_mes.append([nombre_mes, monto])
            else:
                montos_x_mes_fila1.append([nombre_mes, monto])
        """
    #Buscar otros servicios como alquiler parrillero, salón y/o gym
    #Buscar pagos antes de Julio 26
    #generar_recibo_multiconcepto()


if __name__ == "__main__":
    generar_recibo_multiconcepto()

LETRA                                    A
PISO                                     3
NOMBRE Y APELLIDO    JESMY AMANDA PALENQUE
jul-26                              154.05
ago-26                              154.03
sep-26                               154.1
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                NaN
Name: 0, dtype: object
LETRA                                        B
PISO                                         3
NOMBRE Y APELLIDO    NATHALIE CASTRO INOFUENTE
jul-26                                  193.29
ago-26                                  191.44
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                    NaN
Name: 1, dtype: object
LETRA                                    C
PISO                                     3
NOMBRE Y APELLIDO    JOSE MANUEL BUSTILLOS
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                NaN
Name: 2, dtype: object
LETRA                                         D
PISO                                          3
NOMBRE Y APELLIDO    ABDON FELIPE SERNA OLAÑETA
jul-26                                    92.91
ago-26
sep-26                                    93.86
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                     NaN
Name: 3, dtype: object
LETRA                                     E
PISO                                      3
NOMBRE Y APELLIDO    JULIETA MAMANI DE NINA
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi                                 x
Morosos                                   x
escidal                                 NaN
Name: 4, dtype: object
LETRA                                            F
PISO                                             3
NOMBRE Y APELLIDO    BRIGITTE VARGAS/SHAKIRA VIDAL
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                        NaN
Name: 5, dtype: object
LETRA                                  A
PISO                                   4
NOMBRE Y APELLIDO    JULIO RIVERA BRETEL
jul-26                            196.13
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                              NaN
Name: 6, dtype: object
LETRA                                   B
PISO                                    4
NOMBRE Y APELLIDO    MANUEL A. LIRA ORTIZ
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos                                 x
escidal                               NaN
Name: 7, dtype: object
LETRA                                                    C
PISO                                                     4
NOMBRE Y APELLIDO    SIRLEY VALENCIA/ANGEL VALENCVIA SIRPA
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos                                                  x
escidal                                                NaN
Name: 8, dtype: object
LETRA                                   D
PISO                                    4
NOMBRE Y APELLIDO    HAAN CARLA RODRIGUEZ
jul-26                             120.46
ago-26                             115.12
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                               NaN
Name: 9, dtype: object
LETRA                                       E
PISO                                        4
NOMBRE Y APELLIDO    ELIZABETH PAREDES SARDON
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi                                   x
Morosos                                     x
escidal                                   NaN
Name: 10, dtype: object
LETRA                                  F
PISO                                   4
NOMBRE Y APELLIDO    LOURDES LIMA TELLEZ
jul-26                            183.74
ago-26                            187.15
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                              NaN
Name: 11, dtype: object
LETRA                                         A
PISO                                          5
NOMBRE Y APELLIDO    MAIDA MENDIA/ JAIME TAKATA
jul-26                                   224.35
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                     NaN
Name: 12, dtype: object
LETRA                                             B
PISO                                              5
NOMBRE Y APELLIDO    CINTIA ALVARADO/SAMUEL LIMACHI
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos                                           x
escidal                                         NaN
Name: 13, dtype: object
LETRA                                 C
PISO                                  5
NOMBRE Y APELLIDO    LUZ  TICONA QUISPE
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                             NaN
Name: 14, dtype: object
LETRA                                             D
PISO                                              5
NOMBRE Y APELLIDO    MARCELO LOZA/ MARCOS RODRIGUEZ
jul-26                                       147.76
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                         NaN
Name: 15, dtype: object
LETRA                                               E
PISO                                                5
NOMBRE Y APELLIDO    GERMAN HUANCA C./EMILIANA MAMANI
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi                                           x
Morosos                                             x
escidal                                           NaN
Name: 16, dtype: object
LETRA                                       F
PISO                                        5
NOMBRE Y APELLIDO    ROCIO MABEL ALBERTO PATY
jul-26                                 227.59
ago-26                                 232.49
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                   NaN
Name: 17, dtype: object
LETRA                           A
PISO                            6
NOMBRE Y APELLIDO    REYNA VARGAS
jul-26                     166.38
ago-26                     170.31
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                       NaN
Name: 18, dtype: object
LETRA                                                  B
PISO                                                   6
NOMBRE Y APELLIDO    PALMIRA ARANDIA DE CALDERON/BORIS C
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos                                                x
escidal                                              NaN
Name: 19, dtype: object
LETRA                                                   C
PISO                                                    6
NOMBRE Y APELLIDO    ELIANA MOLLINEDO/ SIVILA/MIGUEL AMOS
jul-26                                             161.99
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos                                                 x
escidal                                               NaN
Name: 20, dtype: object
LETRA                                            D
PISO                                             6
NOMBRE Y APELLIDO    NELSON RODRIGUEZ/PAOLA SALMON
jul-26                                      167.31
ago-26                                      171.34
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                        NaN
Name: 21, dtype: object
LETRA                                 E
PISO                                  6
NOMBRE Y APELLIDO    PAULINA CRUZ PINTO
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi                             x
Morosos                               x
escidal                             NaN
Name: 22, dtype: object
LETRA                                     F
PISO                                      6
NOMBRE Y APELLIDO    BEATRIZ GONZALES DURAN
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                 NaN
Name: 23, dtype: object
LETRA                                A
PISO                                 7
NOMBRE Y APELLIDO    EDUARDO FERNANDEZ
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos                              x
escidal                            NaN
Name: 24, dtype: object
LETRA                                                  B
PISO                                                   7
NOMBRE Y APELLIDO    LIDIA ALARCON/HUGO E, ZUZARA CARPIO
jul-26                                            179.76
ago-26                                            178.36
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                              NaN
Name: 25, dtype: object
LETRA                                 C
PISO                                  7
NOMBRE Y APELLIDO    MARIO FLORES LOPEZ
jul-26                           168.37
ago-26                           178.51
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                             NaN
Name: 26, dtype: object
LETRA                                                D
PISO                                                 7
NOMBRE Y APELLIDO    MARTHA LIZARAZU/FROILAN LOPEZ CH.
jul-26                                           92.58
ago-26                                            92.0
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                            NaN
Name: 27, dtype: object
LETRA                          E
PISO                           7
NOMBRE Y APELLIDO    CIDAL LTDA.
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                        x
Name: 28, dtype: object
LETRA                                                F
PISO                                                 7
NOMBRE Y APELLIDO    ROMAN CALDERON/ANGELA TERRAZAS M.
jul-26                                          165.36
ago-26                                          166.64
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                            NaN
Name: 29, dtype: object
LETRA                                           A
PISO                                            8
NOMBRE Y APELLIDO    MOISES CABRERA/ELIANA TORRES
jul-26
ago-26
sep-26                                     219.98
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                       NaN
Name: 30, dtype: object
LETRA                            B
PISO                             8
NOMBRE Y APELLIDO    IRMA ZABALETA
jul-26                      199.14
ago-26                      197.17
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                        NaN
Name: 31, dtype: object
LETRA                                 C
PISO                                  8
NOMBRE Y APELLIDO    CARLOS ALIAGA LIMA
jul-26                           181.53
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                             NaN
Name: 32, dtype: object
LETRA                                            D
PISO                                             8
NOMBRE Y APELLIDO    PAMELA MOLLINEDO/ROXANA PEREZ
jul-26                                      131.26
ago-26                                      131.04
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                        NaN
Name: 33, dtype: object
LETRA                                E
PISO                                 8
NOMBRE Y APELLIDO    WARA SALINAS NINA
jul-26                          242.05
ago-26                          240.18
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi                            x
Morosos
escidal                            NaN
Name: 34, dtype: object
LETRA                                    F
PISO                                     8
NOMBRE Y APELLIDO    MARIA DEL PILAR AMAYA
jul-26                              172.42
ago-26                              182.86
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                NaN
Name: 35, dtype: object
LETRA                             A
PISO                              9
NOMBRE Y APELLIDO    MASSIEL BALBOA
jul-26                       220.61
ago-26                       256.02
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                         NaN
Name: 36, dtype: object
LETRA                                          B
PISO                                           9
NOMBRE Y APELLIDO    PEDRO CALANI/ANA C. DONAIRE
jul-26                                    211.63
ago-26                                    216.89
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos                                        x
escidal                                      NaN
Name: 37, dtype: object
LETRA                                      C
PISO                                       9
NOMBRE Y APELLIDO    VIVIANA CONDORI HUALLPA
jul-26                                156.42
ago-26                                154.82
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                  NaN
Name: 38, dtype: object
LETRA                                    D
PISO                                     9
NOMBRE Y APELLIDO    MARIA EUGENIA MERCADO
jul-26
ago-26                              102.31
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                NaN
Name: 39, dtype: object
LETRA                                          E
PISO                                           9
NOMBRE Y APELLIDO    DORA WILMA VARGAS CALLISAYA
jul-26                                     266.0
ago-26                                    266.14
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi                                      x
Morosos                                        x
escidal                                      NaN
Name: 40, dtype: object
LETRA                                    F
PISO                                     9
NOMBRE Y APELLIDO    REYNA MEDRANO ESCOBAR
jul-26                              149.43
ago-26                              149.49
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                NaN
Name: 41, dtype: object
LETRA                                A
PISO                                10
NOMBRE Y APELLIDO    MARCELO USCAMAITA
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                            NaN
Name: 42, dtype: object
LETRA                                      B
PISO                                      10
NOMBRE Y APELLIDO    JOSE LUIS QUISPE FLORES
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos                                    x
escidal                                  NaN
Name: 43, dtype: object
LETRA                                     C
PISO                                     10
NOMBRE Y APELLIDO    ISAAC CARDENAS MORALES
jul-26                               155.32
ago-26                               155.66
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                 NaN
Name: 44, dtype: object
LETRA                                       D
PISO                                       10
NOMBRE Y APELLIDO    DIEGO QUINTEROS SAAVEDRA
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos                                     x
escidal                                   NaN
Name: 45, dtype: object
LETRA                                  E
PISO                                  10
NOMBRE Y APELLIDO    JIMENA APAZA MAMANI
jul-26                            402.96
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi                              x
Morosos
escidal                              NaN
Name: 46, dtype: object
LETRA                                         F
PISO                                         10
NOMBRE Y APELLIDO    DANIEL GONZALES CUSICANQUI
jul-26                                   192.34
ago-26                                   188.17
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                     NaN
Name: 47, dtype: object
LETRA                                          A
PISO                                          11
NOMBRE Y APELLIDO    NOHELY CARLA  HUANCA ARGANI
jul-26                                    184.42
ago-26                                    176.01
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                      NaN
Name: 48, dtype: object
LETRA                                 B
PISO                                 11
NOMBRE Y APELLIDO    XIMENA ORELLANA B/
jul-26                           179.95
ago-26                           191.41
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                             NaN
Name: 49, dtype: object
LETRA                                               C
PISO                                               11
NOMBRE Y APELLIDO    ANA A. URIA PONCE/ JORGE VASQUEZ
jul-26                                         216.45
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                           NaN
Name: 50, dtype: object
LETRA                                            D
PISO                                            11
NOMBRE Y APELLIDO    LAURA GEMIO/WILMER CABRERA G.
jul-26                                      130.83
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                        NaN
Name: 51, dtype: object
LETRA                          E
PISO                          11
NOMBRE Y APELLIDO    CIDAL LTDA.
jul-26
ago-26
sep-26
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                        x
Name: 52, dtype: object
LETRA                                                    F
PISO                                                    11
NOMBRE Y APELLIDO    ANDREA RODRIGUEZ HUANCA/ CARLOS VALLE
jul-26                                              232.81
ago-26                                              228.91
sep-26                                              229.54
oct-26
nov-26
dic-26
ene-27
feb-27
mar-27
abr-27
may-27
jun-27
3y4 dormi
Morosos
escidal                                                NaN

NameError: name 'nro_recibo' is not defined