# Horas pico

In [2]:
from sqlalchemy import create_engine
engine = create_engine("postgresql://postgres:pgadmin1325@localhost:25432/tauranet_db")
import pandas as pd

In [3]:
query = """
select  
	EXTRACT(HOUR FROM vp.created_at) AS hora,
	pa.importe as ventas
from venta_productos vp
inner join producto_vendidos pv on pv.id_venta_producto = vp.id_venta_producto
inner join pagos as pa on pa.id_venta_producto = pv.id_venta_producto
inner join sucursals s on s.id_sucursal = vp.id_sucursal
where s.id_restaurant = 50
order by hora;
"""

df = pd.read_sql(query, engine)

df.head()

   hora  ventas
0   0.0   120.0
1   0.0   130.0
2   0.0   120.0
3   0.0   130.0
4   0.0    97.5

In [4]:
# df["total_ventas"] = df.groupby("hora")["ventas"].sum()
"""
df = (df.groupby("hora")["ventas"]
        .agg(Ventas = "sum", 
             Pedidos = "count", 
             Ticket_promedio = "mean")
            .round(2)
            .reset_index())
"""
df = (df.groupby("hora")["ventas"]
        .agg(Ventas = "sum", 
             Pedidos = "count", 
             Ticket_promedio = "mean")
            .reset_index())

In [5]:
total_ventas = df["Ventas"].sum()
df

    hora   Ventas  Pedidos  Ticket_promedio
0    0.0   2879.5       20       143.975000
1    8.0   1727.5       15       115.166667
2    9.0   7717.5       89        86.713483
3   10.0  18065.0      165       109.484848
4   11.0  20204.5      150       134.696667
5   12.0  18327.0      176       104.130682
6   13.0   6642.5       63       105.436508
7   14.0   8917.0       73       122.150685
8   15.0   7038.0       71        99.126761
9   16.0  13913.0      132       105.401515
10  17.0  13847.0      113       122.539823
11  18.0   6460.5       66        97.886364
12  19.0   5156.0       43       119.906977
13  20.0   9022.0       99        91.131313
14  21.0   4246.5       46        92.315217
15  22.0   7528.0       71       106.028169
16  23.0   6812.0       42       162.190476

In [6]:
##df["Porcentaje"] = ((df["Ventas"]/total_ventas)*100).round(2)
df["Porcentaje"] = (df["Ventas"]/total_ventas)*100

In [7]:
#Convertir la hora a entero
df["hora"] = df["hora"].astype(int)
# Redondear con dos decimales
df = df.round({
    "hora": 0,
    "Venta": 2,
    "Ticket_promedio": 2,
    "Porcentaje":2
})

In [8]:
# De este reporte se pueden sacar las horas de mas movimiento
df

    hora   Ventas  Pedidos  Ticket_promedio  Porcentaje
0      0   2879.5       20           143.98        1.82
1      8   1727.5       15           115.17        1.09
2      9   7717.5       89            86.71        4.87
3     10  18065.0      165           109.48       11.40
4     11  20204.5      150           134.70       12.75
5     12  18327.0      176           104.13       11.56
6     13   6642.5       63           105.44        4.19
7     14   8917.0       73           122.15        5.63
8     15   7038.0       71            99.13        4.44
9     16  13913.0      132           105.40        8.78
10    17  13847.0      113           122.54        8.74
11    18   6460.5       66            97.89        4.08
12    19   5156.0       43           119.91        3.25
13    20   9022.0       99            91.13        5.69
14    21   4246.5       46            92.32        2.68
15    22   7528.0       71           106.03        4.75
16    23   6812.0       42           162.19        4.30

In [9]:
# Sacar las horas pico, utilizando el 85%

threshold = 0.85

max_sales = df["Ventas"].max()

print(max_sales)

threshold = max_sales * 0.85

print(threshold)

peak_hours = df[
    df["Ventas"] >= threshold
]

print(peak_hours)

20204.5
17173.825
   hora   Ventas  Pedidos  Ticket_promedio  Porcentaje
3    10  18065.0      165           109.48       11.40
4    11  20204.5      150           134.70       12.75
5    12  18327.0      176           104.13       11.56

In [10]:
# Sacar las horas pico, utilizando desviación estandar

mean = df["Ventas"].mean()
std = df["Ventas"].std()

print(mean)
print(std)

horas_pico = df[df["Ventas"] > mean + std]
horas_pico

9323.735294117647
5549.446861843662

   hora   Ventas  Pedidos  Ticket_promedio  Porcentaje
3    10  18065.0      165           109.48       11.40
4    11  20204.5      150           134.70       12.75
5    12  18327.0      176           104.13       11.56

In [11]:
# Detectar franjas de tiempo

hours = horas_pico["hora"].reset_index(drop=True)
#hours = [8,10,11,12,17,19,20]
print(hours)
#hours = sorted(hours)
ranges = []
current = [hours[0]]
print(current)
for h in hours[1:]:
    if h == current[-1] + 1:
        current.append(h)
    else:
        ranges.append(current)
        current = [h]
    
ranges.append(current)
print(ranges)

0    10
1    11
2    12
Name: hora, dtype: int64
[np.int64(10)]
[[np.int64(10), 11, 12]]

## Detectar productos mas vendidos en las horarios pico

Este reporte seria de interes para un resturante grande que tiene venta de muchos productos, pero para restaurantes pequeños de comida rápida que tienen mas de 10 productos no valdria la pena creo yo

In [12]:
#where s.id_restaurant = 50 and EXTRACT(HOUR FROM vp.created_at) between """+ini+""" and """+fin+"""
ini = 0
fin = 0
for rang in ranges:
    if len(rang) == 1:
        ini = fin = rang[0]
    else:
        ini = rang[0]
        fin = rang[-1]
    print(str(ini)+" - "+str(fin))
    query_productosmasvendidos_horaspico = """
    select  
    	p.id_producto,
    	p.nombre,
    	sum(pv.cantidad) as cantidad,
    	sum(pv.p_unit * pv.cantidad) as importe
        from venta_productos vp
        inner join producto_vendidos pv on pv.id_venta_producto = vp.id_venta_producto
        inner join productos p on p.id_producto = pv.id_producto 
        inner join pagos as pa on pa.id_venta_producto = pv.id_venta_producto
        inner join sucursals s on s.id_sucursal = vp.id_sucursal
        where s.id_restaurant = %(id_restaurant)s and EXTRACT(HOUR FROM vp.created_at) between %(ini)s AND %(fin)s
        group by p.id_producto, p.nombre
        order by importe desc;
    """
    df_productosmasvendidos_horaspico = pd.read_sql(
        query_productosmasvendidos_horaspico, 
        engine,
        params={
            "ini": int(ini),
            "fin": int(fin),
            "id_restaurant": 50
        }
    )
    print(df_productosmasvendidos_horaspico)

10 - 12
    id_producto              nombre  cantidad  importe
0           152          Chicharron        51   3040.0
1           159        Costilla BBQ        49   2940.0
2           183        Aji de fideo        33   1485.0
3           175     Chanka de pollo        30   1050.0
4           149             Fricase        20   1000.0
5           160              Lechon        13    910.0
6           157      Coca Cola 2 LT        59    885.0
7           151         Api Orureño        62    620.0
8           161   Hamburguesa doble        10    500.0
9           162  Hamburguesa simple         8    280.0
10          169         Fanta limon        17    255.0
11          154               Limon        30    240.0
12          168       Fanta Naranja        14    210.0
13          150            Yungueño        13    195.0
14          155             Naranja        22    176.0
15          153     Torta chocolate         8    160.0
16          156  Coca cola personal        55    137.5
17          185     Taco de chancho         3    120.0
18          164  Pollo broaster 1/4         4    120.0
19          184  Taco de carne fria         3    105.0
20          178      Sacta de pollo         2     80.0
21          173              Sprite         5     50.0
22          177          Coka Quina         6     48.0
23          172              Sprite         3     45.0
24          186              Paceña         2     44.0
25          170          Coca Quina         4     40.0
26          176       Sopa de pollo         1     30.0
27          158              Sandia         3     30.0
28          166      Paceña litrera         1     24.0
29          163  Pollo broaster 1/8         1     20.0
30          171              Sprite         1      3.5
31          174     Sprite personal         1      3.0