In [1]:
import numpy as np
import pandas as pd

In [33]:
df_alumnos = pd.DataFrame({
    "Nombres": ["Rafael", "Juan", "Carlos"],
    "Apellidos": ["Ortiz Rocha", "Vargas", "Villegas"]
})

df_curso = pd.DataFrame({
    "Curso": ["Computacion", "Psicologia", "Matemáticas"],
    "Modalidad": ["Virtual", "Virtual", "Presencial"]
})

df_notas = pd.DataFrame({
    "1er Parcial": [58, 90, 45],
    "2er Parcial": [60, 85, 35],
    "3er Parcial": [58, 90, 80]
})

df_notas["suma"] = df_notas["1er Parcial"] + df_notas["2er Parcial"] + df_notas["3er Parcial"]

tabla = pd.concat(
    [
        df_alumnos, 
        df_curso,
        df_notas
    ], axis = 1
).fillna(0)

tabla

,Nombres,Apellidos,Curso,Modalidad,1er Parcial,2er Parcial,3er Parcial,suma
0,Rafael,Ortiz Rocha,Computacion,Virtual,58,60,58,176
1,Juan,Vargas,Psicologia,Virtual,90,85,90,265
2,Carlos,Villegas,Matemáticas,Presencial,45,35,80,160

In [19]:
tabla.index.name = "Descripcion"
tabla

            Nombres    Apellidos        Curso  Nota
Descripcion
0            Rafael  Ortiz Rocha  Computacion    85
1              Juan       Vargas   Psicologia    75
2            Carlos     Villegas  Matemáticas    60

In [27]:
tabla.loc["Total"] = tabla.sum()
tabla

,Nombres,Apellidos,Curso,Nota
Descripcion,,,,
0,Rafael,Ortiz Rocha,Computacion,85
1,Juan,Vargas,Psicologia,75
2,Carlos,Villegas,Matemáticas,60
Total,RafaelJuanCarlosRafaelJuanCarlosRafaelJuanCarl...,Ortiz RochaVargasVillegasOrtiz RochaVargasVill...,ComputacionPsicologiaMatemáticasComputacionPsi...,1100

In [30]:
tabla.loc[1, "Apellidos"]

'Vargas'